version: '3'
services:
  php:
    container_name: "curso-php"
    build: .
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 8081:80